"""add unique constrate to role table

Revision ID: d4545c5611e0
Revises: 0139b4ef8c97
Create Date: 2024-06-03 15:36:31.663814

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4545c5611e0"
down_revision: Union[str, None] = "0139b4ef8c97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_role_name"), "role", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_role_name"), "role", type_="unique")
    # ### end Alembic commands ###
