"""add index to foreign keys

Revision ID: b9953ce9ac50
Revises: d4545c5611e0
Create Date: 2024-06-07 10:58:19.352976

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9953ce9ac50"
down_revision: Union[str, None] = "d4545c5611e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_company_information_user_id"),
        "company_information",
        ["user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_role_id"), "user", ["role_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role_id"), table_name="user")
    op.drop_index(
        op.f("ix_company_information_user_id"), table_name="company_information"
    )
    # ### end Alembic commands ###
